[project]
name = 'contracts'
description = ''
authors = []
telemetry = true
cache_dir = '.cache'
requirements = []

[contracts.nft-factory]
path = 'contracts/nft-factory.clar'
clarity_version = 2
epoch = 2.1

[contracts.nft-trait]
path = 'contracts/nft-trait.clar'
clarity_version = 2
epoch = 2.1

[repl.analysis]
passes = [
    'check_checker',
    'check_checker',
]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
